
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: petclinic-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: app01
            imageRepo: 533267075370.dkr.ecr.us-west-2.amazonaws.com/petclinic
            imageTag: "1"
            path: petclinic
            targetRevision: main
          
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{appName}}-image={{imageRepo}}:~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.tag: "~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: "https://github.com/DumalBhaskar/petclinic-helm-manifest.git"
        targetRevision: "main"
        path: "{{path}}"
        # helm:
        #   parameters:
        #     - name: "image.repository"
        #       value: "{{imageRepo}}"
        #     - name: "image.tag"
        #       value: "{{imageTag}}"
        #     - name: "replicaCount"
        #       value: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: "test"
      syncPolicy:
        syncOptions:
         - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
