helm:
  parameters:
  - name: image.repository
    value: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/petclinic
    forcestring: false
  - name: image.tag
    value: " 9-6eafa37"
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/petclinic
    forcestring: true
