replicaCount: 2

image:
  repository: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/petclinic
  tag: "9-6eafa37"
  pullPolicy: IfNotPresent

#imagePullSecrets: ecr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  scheme: internet-facing
  targetType: ip
  host: petclinic.jonathanjo.great-site.net
