replicaCount: 2

image:
  repository: 533267075370.dkr.ecr.us-west-2.amazonaws.com/petclinic
  tag: "1"
  pullPolicy: IfNotPresent

#imagePullSecrets: ecr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  scheme: internet-facing
  targetType: ip
  host: petclinic.zomato.infinityfreeapp.com
